export default [
    {
        id: 1,
        title: "Cotopaxi",
        location: "Latacunga",
        googleMapsUrl: "https://goo.gl/maps/qMQcJeGQhRVkqPTL7",
        startDate: "12 Jan, 2022",
        endDate: "24 Jan, 2022",
        description: "Cotopaxi is one of the most popular climbing sites in Ecuador. Cotopaxi is the second highest point in Ecuador and at 5,897 meters above sea level, its climate is glacial.",
        imageUrl: "https://images.unsplash.com/photo-1606591808963-8fc3c63fa6a2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1102&q=80s",
    },
    {
        id: 2,
        title: "Mitad del Mundo",
        location: "Quito",
        googleMapsUrl: "https://goo.gl/maps/qMQcJeGQhRVkqPTL7",
        startDate: "12 Jan, 2022",
        endDate: "24 Jan, 2022",
        description: "It is a place that sits right on the equatorial line (this is actually why the country got its name, Ecuador) and gives all travelers the option to stand at one moment on both hemispheres.",
        imageUrl: "https://images.unsplash.com/photo-1623190003430-bb4dab53f8ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80",
    },
    {
        id: 3,
        title: "Pinllopata",
        location: "Cotopaxi",
        googleMapsUrl: "https://goo.gl/maps/qMQcJeGQhRVkqPTL7",
        startDate: "12 Jan, 2022",
        endDate: "24 Jan, 2022",
        description: "It is located in the southwest of the province, in the foothills of the western mountain range, and extends into an important region that produces soft corn, barley, wheat, beans, peas, blackberries, broad beans, wood and pasture for livestock.",
        imageUrl: "https://images.unsplash.com/photo-1588414697983-11494810e306?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    },
    {
        id: 4,
        title: "Quilotoa",
        location: "Latacunga",
        googleMapsUrl: "https://goo.gl/maps/qMQcJeGQhRVkqPTL7",
        startDate: "12 Jan, 2022",
        endDate: "24 Jan, 2022",
        description: "Quilotoa crater lake is one of Ecuador's best kept secrets. High up in the Andes, Quilotoa is a large volcanic crater with a mesmerizing emerald green lake in a typical indigenous community.",
        imageUrl: "https://images.unsplash.com/photo-1580918860823-f0072f5a6719?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    },
];